# Release task for PbLib projects
# See https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema for reference

pool:
  vmImage: vs2017-win2016
  demands: Cmd

trigger:
  branches:
    include:
      - refs/tags/*

variables:
  - name: githubConnectionName
    value: Releases
  - name: projectName
    value: yourProjectName #replace this
  - name: githubRepositoryName
    value: yourOrganization/yourRepo #replace this

steps:
- task: BatchScript@1
  displayName: 'FAKE Build'
  inputs:
    filename: build.cmd
    arguments: 'All'

- task: GitHubRelease@0
  displayName: 'GitHub release (create)'
  inputs:
    gitHubConnection: $(githubConnectionName)
    repositoryName: $(githubRepositoryName)
    title: '$(projectName) v$(Build.SourceBranchName)'
    releaseNotesFile: 'RELEASE_NOTES.md'
    assets: |
     bin\nuget\*.nupkg